### ISSUE TITLE
error start-dev-server

### ISSUE THREAD

**Issue by MichaelDanninger** [m-allanson/dbp-prototype#48]
Hi,

i have an issue which may sound really stupid to experts, but i'm new and all i do is going by instructions - that means i'm pretty much f****\* if problems occur.

However, i tried to use the designbypascal-portfolio because i wanted to experiment with this technology of creating static sites rather than putting up my own website with something like wordpress.

Now i always got the error:

"

pm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.5.0/bin/node" "/usr/local/bin/npm" "run" "start:dev"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! designbypascal-portfolio@0.0.1 start:dev: `PORT=8080 DEV_PORT=8081 NODE_ENV=development babel-node ./scripts/start-dev-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the designbypascal-portfolio@0.0.1 start:dev script 'PORT=8080 DEV_PORT=8081 NODE_ENV=development babel-node ./scripts/start-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the designbypascal-portfolio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     PORT=8080 DEV_PORT=8081 NODE_ENV=development babel-node ./scripts/start-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs designbypascal-portfolio
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls designbypascal-portfolio
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

"

I tried to change  the port numbers but it doesn't matter ... still i got this error message. 

Can someone help me? There is so much to learn, i try it with learning by doing and some help would be highly appreciated to understand what is going on.

**Comment by m-allanson** [comment]
Hi @MrMchaD, welcome to GitHub :)

Have you definitely run `npm install` before doing `npm run start:dev`? It looks like the `babel-node` part is what's causing the failure. Running `npm install` should copy all the required files into a `node_modules` folder. 

However if you want to learn about static sites, I would _not_ recommend this project as a starting point. That's because it's not based on an existing static site generator, there's very little documentation, some features are incomplete and there's no community of people around it that might have encountered your problems before you.

Instead, you could try looking at an existing static site generator. That'll have much better docs and usually a good set of 'getting started' guides. Some popular ones are:
- [Jekyll](http://jekyllrb.com/) (written in Ruby)
- [Hexo](https://hexo.io/) (written in Javascript)
- [Sculpin](https://sculpin.io) (written in PHP)

Check out http://www.staticgen.com/ for a longer list. 

Does that help?

**Comment by MichaelDanninger** [comment]
Hello and thank you for your fast response!

It was a mistake by myself, sorry for opening an issue for that but it works perfectly now... for some reason when i moved the folder after the download something went wrong. 

Thank's also for your recommendations, i have some experience with jekyll already and as an autodidact i'm always looking for the next step, that's how i came here.

Again, thank you for your time and response and also for your work!

Sincerely,
Michael

**Comment by m-allanson** [comment]
No problem!
